# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-03 11:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_myuser_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default=datetime.datetime(2018, 10, 3, 11, 35, 36, 812389, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
    ]
