# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-04 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_myuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='username',
        ),
    ]
