# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-04 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181004_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
